module.exports = [
  {
    id: "au.ibm",
    name: "IBM Australia",
    host: "au.stellar.ibm.com",
    port: 11625,
    publicKey: "GCKWUQGSVO45ZV3QK7POYL7HMFWDKWJVMFVEGUJKCAEVUITUCTQWFSM6",
  },
  {
    id: "br.ibm",
    name: "IBM Brazil",
    host: "br.stellar.ibm.com",
    port: 11625,
    publicKey: "GBUJA3Z5TLAKLI5MEH4TETLXJBQVSVW74MNEKP5UUHTP3IMLNSUPOTVA",
  },
  {
    id: "ca.ibm",
    name: "IBM Canada",
    host: "ca.stellar.ibm.com",
    port: 11625,
    publicKey: "GB2HF2NHRKKFZYFDGD7MUENOYROOEK7SWYV2APYOODP6P7BUJTLILKIL",
  },
  {
    id: "no.ibm",
    name: "IBM Norway",
    host: "no.stellar.ibm.com",
    port: 11625,
    publicKey: "GDRA72H7JWXAXWJKOONQOPH3JKNSH5MQ6BO5K74C3X6FO2G3OG464BPU",
  },
  {
    id: "in.ibm",
    name: "IBM India",
    host: "in.stellar.ibm.com",
    port: 11625,
    publicKey: "GCH3O5PTCZVR4G65W3B4XDKWI5V677HQB3QO7CW4YPVYDDFBE2GE7G6V",
  },
  {
    id: "uk.ibm",
    name: "IBM United Kingdom",
    host: "uk.stellar.ibm.com",
    port: 11625,
    publicKey: "GAENPO2XRTTMAJXDWM3E3GAALNLG4HVMKJ4QF525TR25RI42YPEDULOW",
  },
  {
    id: "us.ibm",
    name: "IBM United States",
    host: "us.stellar.ibm.com",
    port: 11625,
    publicKey: "GARBCBH4YSHUJLYEPKEPMVYZIJ3ZSQR3QCJ245CWGY64X72JLN4A6RSG",
  },
  {
    id: "ie.paywith.glass",
    name: "paywith.glass (Ireland)",
    host: "ie.paywith.glass",
    port: 11625,
    publicKey: "GDOQLNMARWIZWLEDKBYBOXP5LQYQQF24PS6NEQW4H766RLD4T7AUWQLB",
  },
  {
    id: "localstellarassets",
    name: "Local Stellar Assets",
    host: "localstellarassets.com",
    port: 11625,
    publicKey: "GA4UHKRQNTYNOI7TMP6ZK2I52UEIBBHAW3LVLBUTSKVRTGDEDTJVKLI3",
  },
  {
    id: "sdf1",
    name: "SDF validator 1",
    host: "core-live-a.stellar.org",
    port: 11625,
    publicKey: "GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH",
  },
  {
    id: "sdf2",
    name: "SDF validator 2",
    host: "core-live-b.stellar.org",
    port: 11625,
    publicKey: "GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK",
  },
  {
    id: "sdf3",
    name: "SDF validator 3",
    host: "core-live-c.stellar.org",
    port: 11625,
    publicKey: "GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ",
  },
  {
    id: "eno",
    name: "Eno",
    host: "stellar.256kw.com",
    port: 11625,
    publicKey: "GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U",
  },
  {
    id: "tempo",
    name: "Tempo",
    host: "stellar1.tempo.eu.com",
    port: 11625,
    publicKey: "GCJCSMSPIWKKPR7WEPIQG63PDF7JGGEENRC33OKVBSPUDIRL6ZZ5M7OO",
  },
  {
    id: "satoshipay1",
    name: "SatoshiPay (DE, Frankfurt)",
    host: "stellar-de-fra.satoshipay.io",
    port: 11625,
    publicKey: "GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE",
  },
  {
    id: "satoshipay2",
    name: "SatoshiPay (SG, Singapore)",
    host: "stellar-sg-sin.satoshipay.io",
    port: 11625,
    publicKey: "GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT",
  },
  {
    id: "satoshipay3",
    name: "SatoshiPay (US, Iowa)",
    host: "stellar-us-iowa.satoshipay.io",
    port: 11625,
    publicKey: "GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY",
  },
  {
    id: "cryptomover1",
    name: "Cryptomover host 1",
    host: "cryptodealer.hk",
    port: 11625,
    publicKey: "GBX7KXY43NOGLCV7TMFFM7UPNM5VGQ52W4IAZNTVMXZ44BHYFESA67N3",
  },
  {
    id: "cryptomover2",
    name: "Cryptomover host 2",
    host: "cryptomover.org",
    port: 11625,
    publicKey: "GC7MH45NSXXPBLQJRSEVF2DFUVLGGYOJER5FRUNVCYVMXJYJT5LLQJW5",
  },
  {
    id: "cryptomover3",
    name: "Cryptomover host 3",
    host: "cryptomover.net",
    port: 11625,
    publicKey: "GCX7S2QY2VXRFDDVVGKRVSMIVGQZQ4NEDYZ3WB7ZUYIVJKMQ4FVVHVR6",
  },
  {
    id: "koinbros",
    name: "Koinbros host 1",
    host: "koinbros.org",
    port: 11625,
    publicKey: "GAE72U4C4MWPG6WAB2XW2EEHPQE3VMG7WRSET5FFDUAMBFR7P462QBC4",
  },
  {
    id: "umbrel",
    name: "umbrel",
    host: "stellar.papayame.com",
    port: 11625,
    publicKey: "GD7FVHL2KUTUYNOJFRUUDJPDRO2MAZJ5KP6EBCU6LKXHYGZDUFBNHXQI",
  },
  {
    id: "ohio1.stellarport",
    name: "Stellarport Ohio 1",
    host: "ohio-1.stellar.stellarport.io",
    port: 11625,
    publicKey: "GBB32UXWEXGZUE7H7LUVNNZRT3ZMZ3YH7SP3V5EFBILUVL3NCTSSK3IZ",
  },
  {
    id: "ohio2.stellarport",
    name: "Stellarport Ohio 2",
    host: "ohio-2.stellar.stellarport.io",
    port: 11625,
    publicKey: "GC5A5WKAPZU5ASNMLNCAMLW7CVHMLJJAKHSZZHE2KWGAJHZ4EW6TQ7PB",
  },
  {
    id: "us1.knackforge",
    name: "KnackForge LLC US 1",
    host: "us1.stellar.knackforge.com",
    port: 11625,
    publicKey: "GAMWPPFIO2ZRR2W2KF73U5M4ONURKLJFAQSE5K5RKQ3LD6FDHNI7SPDI",
  },
  {
    id: "cowrie.exchange",
    name: "Cowrie Exchange",
    host: "stellar.cowriesys.com",
    port: 11625,
    publicKey: "GDAXAGWQNTOUIGTAJDYIL4QCM3Q6HM67SKEAJNSOW6G2Z3QPPKGAVJFW",
  },
  {
    id: "clic.world.2.africa",
    name: "Clic.World 2 (East Africa)",
    host: "stellar2.clic.world",
    port: 11625,
    publicKey: "GDKST4M2OPDPNDZFIZ7CYYFR3SUP4N3GOZIWNVUBAY5VX25X7ZT4RICB",
  },
  {
    id: "de.stellar.goodx.network",
    name: "GoodX Network [DE]",
    host: "de.stellar.goodx.network",
    port: 11625,
    publicKey: "GASN57EFNZWME73BJXYZUTCD34EPX4KIIZQTQDTMBWWVH6JIZJUCBGQX",
  },
  {
    id: "us.stellar.goodx.network",
    name: "GoodX Network [US]",
    host: "us.stellar.goodx.network",
    port: 11625,
    publicKey: "GB7ESEJVQQVNE5DOXVX6UUIF4LDH7E5OVKTIVJ72FPU3AL7XGTY4A6MH",
  },
  {
    id: "v1.stellar.smoove.net",
    name: "smoove.net 1",
    host: "v1.stellar.smoove.net",
    port: 11625,
    publicKey: "GDCAQY2Q5VMMI4ZOX35GTL7X43LMP3RA5W4VCP6V2BB6IFOO76GACXZU",
  },
  {
    id: "v2.stellar.smoove.net",
    name: "smoove.net 2",
    host: "v2.stellar.smoove.net",
    port: 11625,
    publicKey: "GCXEKMPY6TDNNI2VBWFOEA23V22OZW2INSCGTKNEHIHJDPG2C53PURBG",
  },
  {
    id: "keybase",
    name: "keybase.io",
    host: "stellar0.keybase.io",
    port: 11625,
    publicKey: "GCWJKM4EGTGJUVSWUJDPCQEOEP5LHSOFKSA4HALBTOO4T4H3HCHOM6UX",
  },
  {
    id: "us.mobius",
    name: "Mobius (United States)",
    host: "us.stellar.mobius.network",
    port: 11625,
    publicKey: "GB7H5CNUNVCM6KGG6P2LAQE4YZP4D6CHFJRSSS34VNEPDDVIFAWRJ7ZA",
  },
  {
    id: "smartlands",
    name: "Smartlands Platform",
    host: "stellar.smartlands.io",
    port: 11625,
    publicKey: "GCBAQCWXKIIOQOEDIW6EB7GY6UREHPTKK26NZFLVK63ZTRFSXDVX2AHV",
  },
  {
    id: "v1.lobstr",
    name: "LOBSTR 1 (Europe)",
    host: "v1.stellar.lobstr.co",
    port: 11625,
    publicKey: "GCFONE23AB7Y6C5YZOMKUKGETPIAJA4QOYLS5VNS4JHBGKRZCPYHDLW7",
  },
  {
    id: "v2.lobstr",
    name: "LOBSTR 2 (Europe)",
    host: "v2.stellar.lobstr.co",
    port: 11625,
    publicKey: "GDXQB3OMMQ6MGG43PWFBZWBFKBBDUZIVSUDAZZTRAWQZKES2CDSE5HKJ",
  },
  {
    id: "v3.lobstr",
    name: "LOBSTR 3 (North America)",
    host: "v3.stellar.lobstr.co",
    port: 11625,
    publicKey: "GD5QWEVV4GZZTQP46BRXV5CUMMMLP4JTGFD7FWYJJWRL54CELY6JGQ63",
  },
  {
    id: "v4.lobstr",
    name: "LOBSTR 4 (Asia)",
    host: "v4.stellar.lobstr.co",
    port: 11625,
    publicKey: "GA7TEPCBDQKI7JQLQ34ZURRMK44DVYCIGVXQQWNSWAEQR6KB4FMCBT7J",
  },
  {
    id: "v5.lobstr",
    name: "LOBSTR 5 (Australia)",
    host: "v5.stellar.lobstr.co",
    port: 11625,
    publicKey: "GA5STBMV6QDXFDGD62MEHLLHZTPDI77U3PFOD2SELU5RJDHQWBR5NNK7",
  },
  {
    id: "coinqvest-fi",
    name: "COINQVEST (Finland)",
    host: "finland.stellar.coinqvest.com",
    port: 11625,
    publicKey: "GADLA6BJK6VK33EM2IDQM37L5KGVCY5MSHSHVJA4SCNGNUIEOTCR6J5T",
  },
  {
    id: "coinqvest-de",
    name: "COINQVEST (Germany)",
    host: "germany.stellar.coinqvest.com",
    port: 11625,
    publicKey: "GD6SZQV3WEJUH352NTVLKEV2JM2RH266VPEM7EH5QLLI7ZZAALMLNUVN",
  },
  {
    id: "coinqvest-hk",
    name: "COINQVEST (Hong Kong)",
    host: "hongkong.stellar.coinqvest.com",
    port: 11625,
    publicKey: "GAZ437J46SCFPZEDLVGDMKZPLFO77XJ4QVAURSJVRZK2T5S7XUFHXI2Z",
  },
  {
    id: "ocyan_1",
    name: "Ocyan 1",
    host: "stellar.ocyan.com",
    port: 11625,
    publicKey: "GA5MLJBI3PP4I66XZMZZDGOD4NFL3QM7B6EYHEWBWY67FYD3ZO4UZRWV",
  },
  {
    id: "sui",
    name: "stellar.sui.li",
    host: "stellar.sui.li",
    port: 11625,
    publicKey: "GBHMXTHDK7R2IJFUIDIUWMR7VAKKDSIPC6PT5TDKLACEAU3FBAR2XSUI",
  },
  {
    id: "de.sakkex",
    name: "Sakkex Germany",
    host: "de.sakkex.network",
    port: 11625,
    publicKey: "GBTNFYOZ4O5QMFEZ4FCP32VYG4GSGWOUVW3NQI3JMCKCRSDTF7CFA4VW",
  },
  {
    id: "uk.sakkex",
    name: "Sakkex United Kingdom",
    host: "uk.sakkex.network",
    port: 11625,
    publicKey: "GCYAK2RA24YPJKVGFGQY2FWD5VLMBQ3JOY27ZOUVNC3CR7ZETTDLPV7B",
  },
  {
    id: "sg.sakkex",
    name: "Sakkex Singapore",
    host: "sg.sakkex.network",
    port: 11625,
    publicKey: "GDNIGSBNHLXT2HDCEZQUDQU2TPATEXKF5SSPF3UBW4EBHACDOG7IY3PX",
  },
  {
    id: "auskunft.de",
    name: "auskunft.de",
    host: "stellar.auskunft.de",
    port: 11625,
    publicKey: "GBR7I4XGCWLSTKLPYY4IY4QUGW5LYFCMPZOF7OJBMBLLJH5FQVNHWCTD",
  },
  {
    id: "validator1.whitewallet",
    name: "WHITE WALLET 1 (USA)",
    host: "validator1.thewwallet.com",
    port: 11625,
    publicKey: "GBH42X7GG5TQLBMKY2KNYQ6KY7XOUALQCUUZQH5EOLVNULDJMLCNUNJP",
  },
  {
    id: "stellar.tylervault",
    name: "Tyler Vault, Texas",
    host: "stellar.tylervault.com",
    port: 11625,
    publicKey: "GA5UB6D64SV4OLDNCHJJH7YZT2IGKVCPNJVMG5EX5FOIM7WFYRSJLV7B",
  },
  {
    id: "v1.collegecoin.org",
    name: "collegecoin.org",
    host: "v1.stellar.collegecoin.org",
    port: 11625,
    publicKey: "GBATJAZRLNDUIJZEHM3EDRDOT5BUNQ5V3AGEYDOQLHSQXRLYLMK4LXCL",
  },
  {
    id: "sonicwallet.com",
    name: "Sonic Wallet",
    host: "stellar.sonicwallet.com",
    port: 11625,
    publicKey: "GDHDAHSHNXQV3EXHFK76CYIYBEVVBTOFTTJHGNXQ6Z5JMQRJTFKFYSB4",
  },
  {
    id: "uk.wirex",
    name: "Wirex United Kingdom",
    host: "uk.stellar.wirexapp.com",
    port: 11625,
    publicKey: "GBBQQT3EIUSXRJC6TGUCGVA3FVPXVZLGG3OJYACWBEWYBHU46WJLWXEU",
  },
  {
    id: "us.wirex",
    name: "Wirex United States",
    host: "us.stellar.wirexapp.com",
    port: 11625,
    publicKey: "GDXUKFGG76WJC7ACEH3JUPLKM5N5S76QSMNDBONREUXPCZYVPOLFWXUS",
  },
  {
    id: "sg.wirex",
    name: "Wirex Singapore",
    host: "sg.stellar.wirexapp.com",
    port: 11625,
    publicKey: "GAB3GZIE6XAYWXGZUDM4GMFFLJBFMLE2JDPUCWUZXMOMT3NHXDHEWXAS",
  },
  {
    id: "armajeddon",
    name: "ARMAJEDDON",
    host: "armajeddon.com",
    port: 11625,
    publicKey: "GD6GXA2I2FNREL534ZQASLV3U3YJK56KX4V7D5MDX6VIHFBHYVT574PZ",
  },
];
