export const LIVE_NEW_LEDGER = 'LIVE_NEW_LEDGER';
export const LIVE_NEW_OPERATION = 'LIVE_NEW_OPERATION';

export const TEST_NEW_LEDGER = 'TEST_NEW_LEDGER';
export const TEST_NEW_OPERATION = 'TEST_NEW_OPERATION';
